apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: essentials
spec:
  selector:
    app: redis
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
  type: LoadBalancer 